runtime: php74 # Versi PHP yang digunakan

handlers:
  - url: /assets
    static_dir: gs://enhanced-voyage-403808.appspot.com/assets # Mengatur direktori aset statis seperti gambar, CSS, dan JavaScript

  - url: /.*
    script: auto # Mengarahkan semua permintaan lain ke PHP untuk ditangani

env_variables:
  # Definisikan variabel lingkungan jika diperlukan
